language: php

php:
  - 7.1
  - 7.2
  - master


script:
  - ./phpunit --coverage-clover=coverage.xml
  - ./phpunit --configuration ./build/travis-ci-fail.xml > /dev/null; if [ $? -eq 0 ]; then echo "SHOULD FAIL"; false; else echo "fail checked"; fi;
  - xmllint --noout --schema phpunit.xsd phpunit.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration_empty.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration_xinclude.xml -xinclude

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      env: PHPStan
      before_install:
        - travis_retry ./build/tools/composer require --no-update phpunit/php-invoker:^2.0
      install: travis_retry ./build/tools/composer update --prefer-dist --prefer-stable
      script:
        - ./build/tools/phpstan analyse --level=0 src
        - ./build/tools/phpstan analyse --level=2 -c phpstan-tests.neon tests
    - stage: Static Code Analysis
      php: 7.2
      env: php-cs-fixer
      install:
        - phpenv config-rm xdebug.ini
      script:
- ./build/tools/php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff