language: php
dist: trusty
sudo: required

php:
  - 7.0
  - 7.1

before_script:
  - composer install
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs app --standard=PSR2